<a href="https://colab.research.google.com/github/natalkau/pytong/blob/main/tydzien5_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [11]:
print(macierz1)

[3 6 0]


In [15]:
macierz2 = np.array([[1,-1],[0,2],[3,8]])
macierz1 = np.array([[0, 1, 5],[18, 4, 0.5]])

In [16]:
print(macierz1)
print(macierz2)

[[ 0.   1.   5. ]
 [18.   4.   0.5]]
[[ 1 -1]
 [ 0  2]
 [ 3  8]]


In [20]:
zad2 = np.dot(macierz1,macierz2)
print(zad2)

[[15.  42. ]
 [19.5 -6. ]]


In [18]:
A = macierz1
B = macierz2
print("Transponowane A:")
At = A.transpose()
print(At)

Transponowane A:
[[ 0.  18. ]
 [ 1.   4. ]
 [ 5.   0.5]]


In [19]:
print("Transponowane B:")
Bt = B.transpose()
print(Bt)

Transponowane B:
[[ 1  0  3]
 [-1  2  8]]


In [27]:
np.shape(A)

(2, 3)

In [28]:
np.shape(At)

(3, 2)

In [29]:
np.shape(B)

(3, 2)

In [30]:
np.shape(Bt)

(2, 3)

In [25]:
zad4 = np.dot(At,Bt)
print(zad4)

[[-18.   36.  144. ]
 [ -3.    8.   35. ]
 [  4.5   1.   19. ]]


In [31]:
np.shape(zad4)

(3, 3)

In [60]:
i = 0
j = range(3)
print("Zadanie 5 (moja wersja demo):")
for i in j:
  print(f"Rzad {i}: {zad4[i]}")
  i += 1

Zadanie 5 (moja wersja demo):
Rzad 0: [-18.  36. 144.]
Rzad 1: [-3.  8. 35.]
Rzad 2: [ 4.5  1.  19. ]


In [59]:
i = 1
print("Zadanie 5:")
for rzad in zad4:
  print(f"Rzad {i}: {rzad}")
  i += 1

Zadanie 5:
Rzad 1: [-18.  36. 144.]
Rzad 2: [-3.  8. 35.]
Rzad 3: [ 4.5  1.  19. ]


In [57]:
print(At)
Att = At.transpose()
print(Att)
print("Zadanie 6:")
i = 0
j = range(2)
for i in j:
  print(f"Rzad {i}: {Att[i]}")

[[ 0.  18. ]
 [ 1.   4. ]
 [ 5.   0.5]]
[[ 0.   1.   5. ]
 [18.   4.   0.5]]
Zadanie 6:
Rzad 0: [0. 1. 5.]
Rzad 1: [18.   4.   0.5]


In [50]:
print("zadanie 7:")
print("Macierz A:")
print(A)
print("Macierz B:")
print(B)
try:
  suma = A + B
  print(suma)
except ValueError:
  print("Nie da sie ;/")
  print("Rodzaj bledu: ValueError")
  exit(-1)
finally:
  print("Macierze musza miec ten sam shape")

zadanie 7:
Macierz A:
[[ 0.   1.   5. ]
 [18.   4.   0.5]]
Macierz B:
[[ 1 -1]
 [ 0  2]
 [ 3  8]]
Nie da sie ;/
Rodzaj bledu: ValueError
Macierze musza miec ten sam shape


In [65]:
print("Zadanie 8:")
try:
  suma = A + B
  print(suma)
except ValueError:
  print("Zrobilam to juz w zadaniu wyzej xd")
  AB = np.dot(A,B)
  print(AB)
  print(zad4)
  try:
    np.dot(AB, zad4)
  except ValueError:
    print("Nie da sie ich pomnozyc")
    exit(-1)
  exit(-1)

Zadanie 8:
Zrobilam to juz w zadaniu wyzej xd
[[15.  42. ]
 [19.5 -6. ]]
[[-18.   36.  144. ]
 [ -3.    8.   35. ]
 [  4.5   1.   19. ]]
Nie da sie ich pomnozyc


In [68]:
print("Zadanie 9:")
x = input("Wprowadz pierwsza liczbe:")
dzialanie = input("Jesli chcesz pomnozyc, napisz 'x'. Jesli chcesz podzielic, napisz'/'. Jesli chcesz dodac, napisz '+'. Jesli chcesz odjac, napisz '-':")
y = input("Wprowadz druga liczbe:")
x_num = int(x)
y_num = int(y)
if 'x' in dzialanie:
  print(x_num*y_num)
elif '/' in dzialanie:
  if y_num == 0:
    print("Nie mozna dzielic przez 0")
  else:
    print(x_num/y_num)
elif '+' in dzialanie:
  print(x_num+y_num)
elif '-' in dzialanie:
  print(x_num-y_num)

Zadanie 9:
Wprowadz pierwsza liczbe:t
Jesli chcesz pomnozyc, napisz 'x'. Jesli chcesz podzielic, napisz'/'. Jesli chcesz dodac, napisz '+'. Jesli chcesz odjac, napisz '-':+
Wprowadz druga liczbe:x


ValueError: invalid literal for int() with base 10: 't'